### ISSUE TITLE
怎么打飞机？

### ISSUE THREAD

**Issue by danwey** [JR-Dun/CocosPlane#1]
左手还是右手？

**Comment by JR-Dun** [comment]
左右手轮着来可以么






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JR-Dun/CocosPlane"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月10日(星期四) 中午11:12
收件人:&nbsp;"JR-Dun/CocosPlane"<CocosPlane@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JR-Dun/CocosPlane] 怎么打飞机？ (#1)





 
左手还是右手？

**Comment by danwey** [comment]
哈哈哈，可以可以。发点截图呀。看不到效果。
